# Generated by Django 5.0 on 2023-12-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0002_rename_amount_discount_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Процент скидки от общей стоимости заказа', max_digits=5),
        ),
    ]
